// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StundenPlanerDB.Models
{
    public partial class Klasse
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}