// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StundenPlanerDB.Models
{
    public partial class Lehrer
    {
        public Lehrer()
        {
            SchulfachNavigation = new HashSet<Schulfach>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int SchulfachId { get; set; }

        public virtual Schulfach Schulfach { get; set; }
        public virtual ICollection<Schulfach> SchulfachNavigation { get; set; }
    }
}