// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StundenPlanerDB.Models
{
    public partial class Schulfach
    {
        public Schulfach()
        {
            Lehrer = new HashSet<Lehrer>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Raum { get; set; }
        public int LehrerId { get; set; }

        public virtual Lehrer LehrerNavigation { get; set; }
        public virtual ICollection<Lehrer> Lehrer { get; set; }
    }
}